# ============================================================
#  Cl\u00ednica Universitaria UPN \u2014 Configuraci\u00f3n de la aplicaci\u00f3n
#  Este archivo NO debe subirse a git con credenciales reales.
#  En producci\u00f3n, ponlo fuera del proyecto y arranca Tomcat con:
#     -Dclinica.config=/ruta/segura/config.properties
# ============================================================

# ---------- Base de datos ----------
# db.url=jdbc:mysql://localhost:3306/clinica_universitaria?useSSL=false&serverTimezone=UTC
db.url=jdbc:mysql://mysql-clinicagenesis.mysql.database.azure.com:3306/clinica_universitaria?useSSL=true
db.user=Admin123
db.password=Admin123
#db.user=root
#db.password=root

# ---------- Culqui (pasarela de pago) ----------
culqui.public_key=pk_test_XLOyDX8osU79IyYx
culqui.secret_key=sk_test_tqLqASPnS5yQU4MA

# ---------- Nubefact (facturaci\u00f3n SUNAT) ----------
nubefact.ruta=https://api.nubefact.com/api/v1/bfa7f4c8-38eb-4f74-8c69-6b785e01494b
nubefact.token=11a516f4fefc4aa79ad087c1264d2c02b6b72af367d848ab972b8324b75b508f
nubefact.ruc_emisor=10769644739
nubefact.nombre_emisor=CLINICA GENESIS S.A.C.

# ---------- reCAPTCHA (se usar\u00e1 en el Paso 2) ----------
recaptcha.site_key=XXXX
recaptcha.secret_key=XXXX

# ---------- Correo SMTP (se usar\u00e1 en el Paso 3: recuperaci\u00f3n) ----------
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.user=tucorreo@gmail.com
mail.smtp.password=XXXX
mail.from=Clinica UPN <tucorreo@gmail.com>
app.base_url=https://concrete-prior-copious.ngrok-free.dev/ClinicaGenesis

# ---------- Mercado Pago ----------
mercadopago.access_token=APP_USR-7658866463561498-070610-351530c96bbb69aff42d5a35ca9958dd-3523077362